image: quarkus-mandrel.yaml
imageName: quay.io/quarkus/ubi-quarkus-mandrel
buildScript: .github/build-mandrel-images.sh
versions:
  - 20.1.0.0.Alpha1-java11
  - 20.1.0.1.Alpha2-java11
  - 20.1.0.1.Final-java11
  - 20.1.0.2.Final-java11
  - 20.1.0.3.Final-java11
  - 20.2.0.0.Beta1-java11
  - 20.2.0.0.Beta2-java11
  - 20.2.0.0.Final-java11
  - 20.3.0.0.Beta1-java11
  - 20.3.0.0.Beta2-java11
  - 20.3.0.0.Final-java11
tags:
  - id: 20.1-java11
    target: 20.1.0.3.Final-java11
  - id: 20.2-java11
    target: 20.2.0.0.Final-java11
  - id: 20.3-java11
    target: 20.3.0.0.Final-java11
versionCheck: true
