image: quarkus-native-image.yaml
imageName: quay.io/quarkus/ubi-quarkus-native-image
buildScript: .github/build-native-images.sh
versions:
  - 20.3.2-java11
  - 21.1.0-java11
  - 21.1.0-java16
  - 21.2.0-java11
tags:
  - id: 20.3-java11
    target: 20.3.2-java11
  - id: 21.1-java11
    target: 21.1.0-java11
  - id: 21.1-java16
    target: 21.1.0-java16
  - id: 21.2-java11
    target: 21.2.0-java11  
versionCheck: true
