image: quarkus-native-image.yaml
imageName: quay.io/quarkus/ubi-quarkus-native-image
buildScript: .github/build-native-images.sh
versions:
  - 21.2.0-java11
  - 21.2.0-java16
  - 21.3.0-java11
  - 21.3.0-java17
tags:
  - id: 21.2-java11
    target: 21.2.0-java11
  - id: 21.2-java16
    target: 21.2.0-java16
  - id: 21.3-java11
    target: 21.3.0-java11
  - id: 21.3-java17
    target: 21.3.0-java17
versionCheck: true
