image: quarkus-native-s2i.yaml
imageName: quay.io/quarkus/ubi-quarkus-native-s2i
buildScript: .github/build-s2i-native-images.sh
versions:
  - 20.3.2-java11
  - 21.0.0.2-java11
  - 21.1.0-java11
  - 21.1.0-java16
tags:
  - id: 20.3-java11
    target: 20.3.2-java11
  - id: 21.0-java11
    target: 21.0.0.2-java11
  - id: 21.1-java11
    target: 21.1.0-java11
  - id: 21.1-java16
    target: 21.1.0-java16
versionCheck: false
