image: quarkus-tooling.yaml
imageName: quay.io/quarkus/centos-quarkus-maven
buildScript: .github/build-tooling-images.sh
versions:
  - 20.1.0-java11
  - 20.2.0-java11
tags:
  - id: 20.1-java11
    target: 20.1.0-java11
  - id: 20.2-java11
    target: 20.2.0-java11
versionCheck: false
