name: Continuous Integration Build

on:
  pull_request:
      branches:
        - master
  push:
      branches:
        - master
      paths-ignore:
        - '.build/**'

jobs:

  native-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build native-image images
      run: jbang/bin/jbang .github/build-native-images.java      

  mandrel-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build mandrel images
      run: jbang/bin/jbang .github/build-mandrel-images.java

  native-s2i:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (native) images
      run: jbang/bin/jbang .github/build-s2i-native-images.java    

  binary-s2i:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (binary) images
      run: .github/build-s2i-binary-images.sh        

  tooling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build tooling images
      run: jbang/bin/jbang .github/build-tooling-images.java    

