name: Continuous Integration Build

on:
  pull_request:
      branches:
        - master
  push:
      branches:
        - master
      paths-ignore:
        - '.build/**'

jobs:

  native-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build native-image images
      run: .github/build-native-images.sh

  mandrel-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build mandrel images
      run: .github/build-mandrel-images.sh

  native-s2i:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (native) images
      run: .github/build-s2i-native-images.sh  

  binary-s2i:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (binary) images
      run: .github/build-s2i-binary-images.sh        

  tooling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build tooling images
      run: .github/build-tooling-images.sh              
