name: Push Images to Quay
on:
  deployment:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  native-image-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build native-image images
      run: .github/build-native-images.sh
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh                            

  mandrel-image-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build mandrel images
      run: .github/build-mandrel-images.sh
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh

  native-s2i-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (native) images
      run: .github/build-s2i-native-images.sh  
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh                            

  binary-s2i-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (binary) images
      run: .github/build-s2i-binary-images.sh        
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh                                

  tooling-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build tooling images
      run: .github/build-tooling-images.sh              
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh
